### ISSUE TITLE
BrowserslistError: Unknown browser query `op_mini all`

### ISSUE THREAD

**Issue by cattermo** [ai/browserslist#104]
With the latest version of browserslist I get this error (using postcss-loader and webpack)
```
ModuleBuildError: Module build failed: BrowserslistError: Unknown browser query `op_mini all`
    at error (C:\Users\claatt\Documents\Projects\external-web-aem\node_modules\browserslist\index.js:23:15)
    at C:\Users\claatt\Documents\Projects\external-web-aem\node_modules\browserslist\index.js:123:13
    at Array.forEach (native)
    at browserslist (C:\Users\claatt\Documents\Projects\external-web-aem\node_modules\browserslist\index.js:95:16)
    at isSupported (C:\Users\claatt\Documents\Projects\external-web-aem\node_modules\caniuse-api\dist\index.js:75:10)
    at C:\Users\claatt\Documents\Projects\external-web-aem\node_modules\postcss-merge-rules\dist\lib\ensureCompatibility.js:87:66
    at C:\Users\claatt\Documents\Projects\external-web-aem\node_modules\postcss-selector-parser\dist\selectors\container.js:170:26
    at Selector.each (C:\Users\claatt\Documents\Projects\external-web-aem\node_modules\postcss-selector-parser\dist\selectors\container.js:153:22)
    at Selector.walk (C:\Users\claatt\Documents\Projects\external-web-aem\node_modules\postcss-selector-parser\dist\selectors\container.js:169:21)
    at C:\Users\claatt\Documents\Projects\external-web-aem\node_modules\postcss-selector-parser\dist\selectors\container.js:173:31
    at Root.each (C:\Users\claatt\Documents\Projects\external-web-aem\node_modules\postcss-selector-parser\dist\selectors\container.js:153:22)
    at Root.walk (C:\Users\claatt\Documents\Projects\external-web-aem\node_modules\postcss-selector-parser\dist\selectors\container.js:169:21)
    at Processor.func (C:\Users\claatt\Documents\Projects\external-web-aem\node_modules\postcss-merge-rules\dist\lib\ensureCompatibility.js:80:17)
    at Processor.process (C:\Users\claatt\Documents\Projects\external-web-aem\node_modules\postcss-selector-parser\dist\processor.js:34:14)
    at C:\Users\claatt\Documents\Projects\external-web-aem\node_modules\postcss-merge-rules\dist\lib\ensureCompatibility.js:121:12
    at Array.every (native)
    at ensureCompatibility (C:\Users\claatt\Documents\Projects\external-web-aem\node_modules\postcss-merge-rules\dist\lib\ensureCompatibility.js:77:22)
    at canMerge (C:\Users\claatt\Documents\Projects\external-web-aem\node_modules\postcss-merge-rules\dist\index.js:74:44)
    at C:\Users\claatt\Documents\Projects\external-web-aem\node_modules\postcss-merge-rules\dist\index.js:222:24
    at C:\Users\claatt\Documents\Projects\external-web-aem\node_modules\postcss\lib\container.js:241:28
    at C:\Users\claatt\Documents\Projects\external-web-aem\node_modules\postcss\lib\container.js:148:26
    at Root.each (C:\Users\claatt\Documents\Projects\external-web-aem\node_modules\postcss\lib\container.js:114:22)
    at Root.walk (C:\Users\claatt\Documents\Projects\external-web-aem\node_modules\postcss\lib\container.js:147:21)
    at Root.walkRules (C:\Users\claatt\Documents\Projects\external-web-aem\node_modules\postcss\lib\container.js:239:25)
    at C:\Users\claatt\Documents\Projects\external-web-aem\node_modules\postcss-merge-rules\dist\index.js:274:13
    at LazyResult.run (C:\Users\claatt\Documents\Projects\external-web-aem\node_modules\postcss\lib\lazy-result.js:276:20)
    at C:\Users\claatt\Documents\Projects\external-web-aem\node_modules\postcss\lib\lazy-result.js:190:37
    at LazyResult.asyncTick (C:\Users\claatt\Documents\Projects\external-web-aem\node_modules\postcss\lib\lazy-result.js:204:15)
    at C:\Users\claatt\Documents\Projects\external-web-aem\node_modules\postcss\lib\lazy-result.js:202:27
    at LazyResult.asyncTick (C:\Users\claatt\Documents\Projects\external-web-aem\node_modules\postcss\lib\lazy-result.js:204:15)
    at DependenciesBlock.onModuleBuildFailed (C:\Users\claatt\AppData\Roaming\npm\node_modules\webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:315:19)
    at nextLoader (C:\Users\claatt\AppData\Roaming\npm\node_modules\webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:270:31)
    at C:\Users\claatt\AppData\Roaming\npm\node_modules\webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:292:15
    at context.callback (C:\Users\claatt\AppData\Roaming\npm\node_modules\webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:148:14)
    at Object.<anonymous> (C:\Users\claatt\Documents\Projects\external-web-aem\node_modules\css-loader\lib\loader.js:32:18)
    at C:\Users\claatt\Documents\Projects\external-web-aem\node_modules\css-loader\lib\processCss.js:211:3
```

Everything is fine when downgrading to 1.5.1. 
From my webpack.config:
```
config.postcss = [
    autoprefixer({
      browsers: ['last 4 version', 'IE 10', 'IE 9']
    })
  ];
```

**Comment by ai** [comment]
It happens because of old version of Browserslist inside your dependencies.

I will try to find bad dependency tomorrow. But maybe it is `postcss-selector-parser`.

**Comment by cattermo** [comment]
Ah, I see, as soon as I added browserslist as a local dependency it started working because that version was used instead. I will keep the local dependency for now then.

**Comment by cattermo** [comment]
An old version of ```postcss-loader``` was the problem. When I updated to latest I could remove browserslist as local dependency.
Thank you for pointing me in the right direction!
