### ISSUE TITLE
Browserlist throws an error on unknown browser version

### ISSUE THREAD

**Issue by handijk** [ai/browserslist#105]
Caniuse does not seem to know and_chr version 55 yet.
Seems to be related to #10 

{ BrowserslistError: Unknown version 55 of and_chr
    at error (/pipeline/source/node_modules/browserslist/index.js:25:15)
    at Function.select (/pipeline/source/node_modules/browserslist/index.js:458:21)
    at /pipeline/source/node_modules/browserslist/index.js:111:38
    at Array.forEach (native)
    at browserslist (/pipeline/source/node_modules/browserslist/index.js:97:16)
    at isSupported (/pipeline/source/node_modules/caniuse-api/dist/index.js:75:10)
    at /pipeline/source/node_modules/postcss-merge-rules/dist/lib/ensureCompatibility.js:87:66
    at /pipeline/source/node_modules/postcss-selector-parser/dist/selectors/container.js:170:26
    at Selector.each (/pipeline/source/node_modules/postcss-selector-parser/dist/selectors/container.js:153:22)
    at Selector.walk (/pipeline/source/node_modules/postcss-selector-parser/dist/selectors/container.js:169:21)
  name: 'BrowserslistError',
  message: 'Unknown version 55 of and_chr',
  browserslist: true }

**Comment by ai** [comment]
Can I use data contains only `and_chr 51`. If you want to fix it, write to Can I Use :).
