### ISSUE TITLE
BrowserslistError: Unknown version 55 of and_chr

### ISSUE THREAD

**Issue by spaceribs** [ai/browserslist#106]
Recently, when running my css-loader with minification through webpack, i'm getting the following error:

```
ERROR in ./~/css-loader?minimize!./~/sass-loader!./src/static/components/profileImage/profileImage.scss
    Module build failed: BrowserslistError: Unknown version 55 of and_chr
        at error (/.../node_modules/browserslist/index.js:25:15)
        at Function.select (/.../node_modules/browserslist/index.js:458:21)
        at /.../node_modules/browserslist/index.js:111:38
        at Array.forEach (native)
        at browserslist (/.../node_modules/browserslist/index.js:97:16)
        at isSupported (/.../node_modules/caniuse-api/dist/index.js:75:10)
        at /.../node_modules/postcss-merge-rules/dist/lib/ensureCompatibility.js:87:66
        at /.../node_modules/postcss-selector-parser/dist/selectors/container.js:170:26
        at Selector.each (/.../node_modules/postcss-selector-parser/dist/selectors/container.js:153:22)
        at Selector.walk (/.../node_modules/postcss-selector-parser/dist/selectors/container.js:169:21)
        at /.../node_modules/postcss-selector-parser/dist/selectors/container.js:173:31
        at Root.each (/.../node_modules/postcss-selector-parser/dist/selectors/container.js:153:22)
        at Root.walk (/.../node_modules/postcss-selector-parser/dist/selectors/container.js:169:21)
        at Processor.func (/.../node_modules/postcss-merge-rules/dist/lib/ensureCompatibility.js:80:17)
        at Processor.process (/.../node_modules/postcss-selector-parser/dist/processor.js:34:14)
        at /.../node_modules/postcss-merge-rules/dist/lib/ensureCompatibility.js:121:12
```

I'm hoping it's just a quick update, but I couldn't find any other issues posted about it.

**Comment by spaceribs** [comment]
It looks like I was using an old version of css-loader, deleting my node modules entirely and reinstalling did the trick.
