### ISSUE TITLE
BrowserslistError: Unknown version 55 of and_chr

### ISSUE THREAD

**Issue by ben-eb** [ai/browserslist#128]
The error occurs with the following custom usage data:

```json
{
    "and_chr": {
        "55": 14.063696426229837
    }
}
```

& the following browserslist config in `package.json`:

```json
{
  "browserslist": [
    "last 3 Chrome versions",
    "last 3 Firefox versions",
    "last 2 Safari versions",
    "last 3 Edge versions",
    "last 2 iOS versions",
    "last 2 Android versions",
    "last 2 ChromeAndroid versions",
    "IE >= 11",
    "> 0.2% in my stats"
  ]
}
```

Right now a temporary fix is setting the version key to `0` instead of `55`, otherwise this error is thrown:

```
BrowserslistError: Unknown version 55 of and_chr
    at error (/Users/beneb/projects/mergerules-bug-test/node_modules/browserslist/index.js:37:11)
    at Function.select (/Users/beneb/projects/mergerules-bug-test/node_modules/browserslist/index.js:603:21)
    at /Users/beneb/projects/mergerules-bug-test/node_modules/browserslist/index.js:207:41
    at Array.forEach (native)
    at browserslist (/Users/beneb/projects/mergerules-bug-test/node_modules/browserslist/index.js:196:13)
```

Thanks to @notacouch for providing a test case which reproduces the error! 💯

https://github.com/notacouch/mergerules-bug-test/commit/4d7b1be44aa75683851beec8169a3fc02cdb0361

**Comment by ai** [comment]
Are you sure, that you use latest version? I can’t reproduce it on `master` :-/

**Comment by ben-eb** [comment]
Yeah, this is with a fresh install:

```
$ npm ls --depth 1
mergerules-bug-test@0.0.0 /Users/beneb/projects/mergerules-bug-test
├─┬ autoprefixer@6.7.6
│ ├── caniuse-db@1.0.30000631
│ ├── normalize-range@0.1.2
│ ├── num2fraction@1.2.2
│ ├── postcss@5.2.15
│ └── postcss-value-parser@3.3.0
├─┬ browserslist@1.7.5
│ └── electron-to-chromium@1.2.5
├─┬ gulp@3.9.1
│ ├── archy@1.0.0
│ ├── chalk@1.1.3
│ ├── deprecated@0.0.1
│ ├── interpret@1.0.1
│ ├── liftoff@2.3.0
│ ├── minimist@1.2.0
│ ├── orchestrator@0.3.8
│ ├── pretty-hrtime@1.0.3
│ ├── semver@4.3.6
│ ├── tildify@1.2.0
│ ├── v8flags@2.0.11
│ └── vinyl-fs@0.3.14
├─┬ gulp-changed@1.3.2
│ └── through2@2.0.3
├─┬ gulp-cssnano@2.1.2
│ ├── cssnano@3.10.0
│ ├── object-assign@4.1.1
│ └── vinyl-sourcemaps-apply@0.2.1
├── gulp-flatten@0.2.0
├── gulp-rename@1.2.2
└─┬ gulp-util@3.0.8
  ├── array-differ@1.0.0
  ├── array-uniq@1.0.3
  ├── beeper@1.1.1
  ├── dateformat@2.0.0
  ├── fancy-log@1.3.0
  ├── gulplog@1.0.0
  ├── has-gulplog@0.1.0
  ├── lodash._reescape@3.0.0
  ├── lodash._reevaluate@3.0.0
  ├── lodash._reinterpolate@3.0.0
  ├── lodash.template@3.6.2
  ├── multipipe@0.1.2
  ├── object-assign@3.0.0
  ├── replace-ext@0.0.1
  └── vinyl@0.5.3
```

**Comment by ai** [comment]
I think it could fix a problem https://github.com/ai/browserslist/commit/6df42c605d29fb948007baca6472dea217dca1f5

**Comment by ai** [comment]
Released in 1.7.6

**Comment by ben-eb** [comment]
Confirmed fixed! Thanks. 🎉

**Comment by notacouch** [comment]
Thanks, all! Great work.
