### ISSUE TITLE
browserslist file doesn't support comments

### ISSUE THREAD

**Issue by ch2ch3** [ai/browserslist#135]
Hey there, when I add a comment to the top of my browserslist file, I get the error:

```
BrowserslistError: Unknown browser query `# TODO: [my comment]`
    at error (/home/site/node_modules/browserslist/index.js:37:11)
    at /home/site/node_modules/browserslist/index.js:222:9
    at Array.forEach (native)
    at browserslist (/home/site/node_modules/browserslist/index.js:196:13)
    at new BrowserSelection (/home/site/node_modules/doiuse/lib/browsers.js:17:18)
    at missing (/home/site/node_modules/doiuse/lib/missing-support.js:76:18)
    at doiuse (/home/site/node_modules/doiuse/lib/doiuse.js:42:25)
    at /home/site/node_modules/stylelint/lib/rules/no-unsupported-browser-features/index.js:41:5
    at Promise.resolve.then (/home/site/node_modules/stylelint/lib/lintSource.js:122:52)
```

This was surprising considering the example in the README:

```
# Browsers that we support

> 1%
Last 2 versions
IE 10 # sorry
```

I'm using browserslist 1.7.7.

**Comment by ai** [comment]
Please show your config.

**Comment by ch2ch3** [comment]
My config:

```
# TODO: discuss with TL team

last 2 versions
> 5%
```

Removing the topmost comment works perfectly.

**Comment by ai** [comment]
Strange. I will look tomorrow (sorry, going to sleep right now).

Could you show your project structure?

**Comment by ch2ch3** [comment]
Sure, no worries.

I can share the relevant bits: I'm using browserslist for stylelint, and cssnext (through PostCSS). The command I use for stylelint is `stylelint src/**/*.css`. I'm also running this in Docker, but I have tried locally with no difference. 

.stylelintrc.js:

```js
module.exports = {
  "extends": "stylelint-config-standard",
  "rules": {
    "no-unsupported-browser-features": true,
  },
};
```

postcss.config.js:

```js
module.exports = {
  plugins: {
    'postcss-import': {
      addModulesDirectories: [
        ...process.env.NODE_PATH.split(':'),
      ],
    },
    'postcss-cssnext': {},
  },
};
```

dependencies:

```
  "dependencies": {
    "bunyan": "1.8.5",
    "bunyan-middleware": "0.6.0",
    "body-parser": "1.16.0",
    "classnames": "2.2.5",
    "ejs": "2.5.5",
    "es6-promise": "4.0.5",
    "express": "4.13.3",
    "form-data": "2.1.2",
    "isomorphic-fetch": "2.2.1",
    "lodash": "4.17.4",
    "mysql2": "1.2.0",
    "react": "15.4.2",
    "react-dom": "15.4.2",
    "react-redux": "5.0.2",
    "redux": "3.6.0",
    "redux-little-router": "12.1.2",
    "redux-logger": "2.8.2",
    "redux-thunk": "2.2.0"
  },
  "devDependencies": {
    "babel-core": "6.22.1",
    "babel-eslint": "7.2.1",
    "babel-loader": "6.2.10",
    "babel-preset-es2015": "6.22.0",
    "babel-preset-react": "6.22.0",
    "babel-preset-stage-3": "6.22.0",
    "babel-register": "6.23.0",
    "chai": "3.5.0",
    "css-loader": "0.27.2",
    "dirty-chai": "1.2.2",
    "enzyme": "2.7.1",
    "eslint": "3.19.0",
    "eslint-config-airbnb": "14.1.0",
    "eslint-plugin-import": "2.2.0",
    "eslint-plugin-jsx-a11y": "4.0.0",
    "eslint-plugin-react": "6.9.0",
    "extract-text-webpack-plugin": "2.1.0",
    "flow-bin": "0.39.0",
    "mocha": "3.2.0",
    "postcss": "5.2.16",
    "postcss-cssnext": "2.9.0",
    "postcss-import": "9.1.0",
    "postcss-loader": "1.3.3",
    "proxyquire": "1.7.11",
    "react-addons-test-utils": "15.4.2",
    "react-hot-loader": "3.0.0-beta.6",
    "sinon": "1.17.7",
    "sinon-as-promised": "4.0.2",
    "sinon-chai": "2.8.0",
    "source-map-support": "0.4.11",
    "style-loader": "0.13.2",
    "stylelint": "7.7.1",
    "stylelint-config-standard": "15.0.1",
    "stylelint-order": "0.4.3",
    "webpack": "2.2.1",
    "webpack-dev-middleware": "1.10.0",
    "webpack-hot-middleware": "2.16.1",
    "webpack-node-externals": "1.5.4"
  }
```

**Comment by ai** [comment]
I tested your config and everything works perfect. 

Also we have config with comment in tests: https://github.com/ai/browserslist/blob/master/test/fixtures/browserslist

So seems like it is environment problem here. Could you create small project to reproduce problem?

**Comment by ch2ch3** [comment]
Thanks for looking into it @ai, I'll try to get a reproduction soon :)

**Comment by ch2ch3** [comment]
Hi @ai, check out https://github.com/ch2ch3/browserslist-comments. Run `npm install && npm run lint:css` and you should see the issue. I've added the debug log to the repository as well.

**Comment by ai** [comment]
I found problem — doiuse uses Browserslist in completely wrong way. I created a issue to fix it: https://github.com/anandthakker/doiuse/issues/67
