### ISSUE TITLE
[caniuse-lite]Compatibility problems

### ISSUE THREAD

**Issue by An0nymous0** [ai/browserslist#165]
no problem:"caniuse-lite": "1.0.30000697"

There is a problem:"caniuse-lite": "1.0.30000712"

Module build failed: Error: Cannot find module 'caniuse-lite' (While processing preset: "/usr/local/openresty/nginx/html/study-manage/node_modules/babel-preset-env/lib/index.js")
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/openresty/nginx/html/study-manage/node_modules/babel-preset-env/node_modules/browserslist/index.js:5:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/openresty/nginx/html/study-manage/node_modules/babel-preset-env/lib/targets-parser.js:5:21)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/openresty/nginx/html/study-manage/node_modules/babel-preset-env/lib/index.js:33:22)
    at Module._compile (module.js:569:30)
 @ multi babel-polyfill ./src/main.js[39m[22m

**Comment by An0nymous0** [comment]
demo link : https://github.com/An0nymous0/error-demo

**Comment by ai** [comment]
Seems like it is a problem with your npm/yarn.

**Comment by An0nymous0** [comment]
@ai  thx

**Comment by An0nymous0** [comment]
@ai Yarn installation can exist under the node_models directory caniuse-lite/dist/unpacker/agents file and caniuse-lite/dist/unpacker/region, this situation may also be the reason?

**Comment by ai** [comment]
Sorry, didn’t get what situation. Can you show some examples?
