### ISSUE TITLE
1.5.0: Error if browserslist and package.json files are in the same directory

### ISSUE THREAD

**Issue by onemeta** [ai/browserslist#95]
This was not the case in 1.4.0. My package.json does not contain any configuration for browserslist.

I redacted the folder structure for brevity, but this is the stack trace:

BrowserslistError: C:\[project folder] contains both browserslist and package.json with browsers
    at error (C:\[project folder]\node_modules\browserslist\index.js:29:11)
    at C:\[project folder]\node_modules\browserslist\index.js:309:13
    at eachParent (C:\[project folder]\node_modules\browserslist\index.js:59:22)
    at Function.browserslist.findConfig (C:\[project folder]\node_modules\browserslist\index.js:304:12)
    at browserslist (C:\[project folder]\node_modules\browserslist\index.js:134:44)
    at cleanBrowsersList (C:\[project folder]\node_modules\caniuse-api\dist\utils.js:52:15)
    at setBrowserScope (C:\[project folder]\node_modules\caniuse-api\dist\index.js:27:14)
    at Object.<anonymous> (C:\[project folder]\node_modules\caniuse-api\dist\index.js:101:1)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)

**Comment by onemeta** [comment]
BrowserslistError: C:\[project folder] contains both browserslist and package.json with browsers
    at error (C:\[project folder]\node_modules\browserslist\index.js:29:11)
    at C:\[project folder]\node_modules\browserslist\index.js:309:13
    at eachParent (C:\[project folder]\node_modules\browserslist\index.js:59:22)
    at Function.browserslist.findConfig (C:\[project folder]\node_modules\browserslist\index.js:304:12)
    at browserslist (C:\[project folder]\node_modules\browserslist\index.js:134:44)
    at cleanBrowsersList (C:\[project folder]\node_modules\caniuse-api\dist\utils.js:52:15)
    at setBrowserScope (C:\[project folder]\node_modules\caniuse-api\dist\index.js:27:14)
    at Object.<anonymous> (C:\[project folder]\node_modules\caniuse-api\dist\index.js:101:1)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)

**Comment by ai** [comment]
@onemeta could you show your project structure?

**Comment by ai** [comment]
Fixed ce975d5

**Comment by ai** [comment]
Fixed ce975d5

**Comment by ai** [comment]
Released in 1.5.1

**Comment by onemeta** [comment]
Looks to be working now. Thanks!
